CONFIG_SYS_TIMER_COUNTS_DOWN=y
CONFIG_SYS_MMCSD_FS_BOOT_PARTITION=y
CONFIG_SYS_SPI_U_BOOT_OFFS=0x100000
CONFIG_BOOTM_NETBSD=y
CONFIG_BOOTM_VXWORKS=y
CONFIG_IS_MODULE(option)="config_enabled(CONFIG_VAL(option ##_MODULE))"
CONFIG_SYS_LOAD_ADDR=0
CONFIG_SYS_HELP_CMD_WIDTH=10
CONFIG_BOOTM_RTEMS=y
CONFIG_SYS_CBSIZE=256
CONFIG_BOOTM_LINUX=y
CONFIG_SYS_LDSCRIPT="arch/arm/mach-zynq/u-boot.lds"
CONFIG_THOR_RESET_OFF=y
CONFIG_SYS_SPL_MALLOC_SIZE=0x2000000
CONFIG_SYS_SPL_ARGS_ADDR=0x10000000
CONFIG_ENV_OVERWRITE=y
CONFIG_SPL_BUILD=y
CONFIG_SYS_BOOTM_LEN="(60 * 1024 * 1024)"
CONFIG_SPL_FS_LOAD_ARGS_NAME="system.dtb"
CONFIG_SYS_MMCSD_RAW_MODE_ARGS_SECTOR=0
CONFIG_ARM_DCC=y
CONFIG_BOOTM_PLAN9=y
CONFIG_IS_BUILTIN(option)="config_enabled(CONFIG_VAL(option))"
CONFIG_SYS_MAXARGS=32
CONFIG_SYS_PBSIZE="(CONFIG_SYS_CBSIZE + sizeof(CONFIG_SYS_PROMPT) + 16)"
CONFIG_BOARDDIR="board/xilinx/zynq"
CONFIG_SPL_LOAD_FIT_ADDRESS=0x10000000
CONFIG_SPL_STACK=0xfffffe00
CONFIG_CPU_FREQ_HZ=800000000
CONFIG_REMAKE_ELF=y
CONFIG_SYS_L2CACHE_OFF=y
CONFIG_BOOTP_MAY_FAIL=y
CONFIG_SYS_DFU_DATA_BUF_SIZE=0x600000
CONFIG_SYS_MMCSD_RAW_MODE_ARGS_SECTORS=0
CONFIG_SYS_INIT_RAM_SIZE=0x1000
CONFIG_SYS_SPI_ARGS_OFFS=0x200000
CONFIG_SYS_BAUDRATE_TABLE="{300, 600, 1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200, 230400}"
CONFIG_VAL(option)="config_val(option)"
CONFIG_SYS_DCACHE_OFF=y
CONFIG_SYS_BOOT_RAMDISK_HIGH=y
CONFIG_SYS_TIMER_COUNTER="(CONFIG_SYS_TIMERBASE + 0x4)"
CONFIG_SYS_SPL_MALLOC_START=$(CONFIG_SPL_STACK_R_ADDR)
CONFIG_SYS_TIMERBASE="ZYNQ_SCUTIMER_BASEADDR"
CONFIG_SYS_INIT_RAM_ADDR=0xFFFF0000
CONFIG_SPL_BSS_MAX_SIZE=0x100000
CONFIG_SPL_FS_LOAD_KERNEL_NAME="uImage"
CONFIG_SPL_BSS_START_ADDR=0x100000
CONFIG_SPL_PAD_TO=$(CONFIG_SPL_MAX_SIZE)
CONFIG_EXTRA_ENV_SETTINGS=""fit_image=fit.itb0load_addr=0x20000000fit_size=0x8000000flash_off=0x1000000nor_flash_off=0xE21000000fdt_high=0x200000000initrd_high=0x200000000scriptaddr=0x200000script_offser_nor=0xE2FC00000script_offset_f=0xFC00000script_size_f=0x400000loadbootenv_addr=0x20000000fdt_addr_r=0x1f000000pxefile_addr_r=0x20000000kernel_addr_r=0x20000000scriptaddr=0x30000000ramdisk_addr_r=0x31000000bootenv=uEnv.txt0bootenv_dev=mmc0loadbootenv=load ${bootenv_dev} 0 ${loadbootenv_addr} ${bootenv}0importbootenv=echo Importing environment from ${bootenv_dev} ...; env import -t ${loadbootenv_addr} $filesize0bootenv_existence_test=test -e ${bootenv_dev} 0 /${bootenv}0setbootenv=if env run bootenv_existence_test; then if env run loadbootenv; then env run importbootenv; fi; fi; 0sd_loadbootenv=setenv bootenv_dev mmc && run setbootenv 0usb_loadbootenv=setenv bootenv_dev usb && usb start && run setbootenv 0preboot=if test $modeboot = sdboot; then run sd_loadbootenv; echo Checking if uenvcmd is set ...; if test -n $uenvcmd; then echo Running uenvcmd ...; run uenvcmd; fi; fi; 0norboot=echo Copying FIT from NOR flash to RAM... && cp.b ${nor_flash_off} ${load_addr} ${fit_size} && bootm ${load_addr}0sdboot=echo Copying FIT from SD to RAM... && load mmc 0 ${load_addr} ${fit_image} && bootm ${load_addr}0jtagboot=echo TFTPing FIT to RAM... && tftpboot ${load_addr} ${fit_image} && bootm ${load_addr}0usbboot=if usb start; then echo Copying FIT from USB to RAM... && load usb 0 ${load_addr} ${fit_image} && bootm ${load_addr}; fi0" DFU_ALT_INFO BOOTENV"
CONFIG_SYS_INIT_SP_ADDR="(CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)"
CONFIG_SYS_MMC_MAX_DEVICE=y
CONFIG_USB_CABLE_CHECK=y
CONFIG_SYS_UBOOT_START=$(CONFIG_SYS_TEXT_BASE)
CONFIG_SYS_MEMTEST_END=0x1000
CONFIG_SPL_MAX_SIZE=0x30000
CONFIG_SYS_SPI_KERNEL_OFFS="(CONFIG_SYS_SPI_ARGS_OFFS + CONFIG_SYS_SPI_ARGS_SIZE)"
CONFIG_CLOCKS=y
CONFIG_SYS_FAULT_ECHO_LINK_DOWN=y
CONFIG_SYS_MEMTEST_START=0
CONFIG_LMB=y
CONFIG_SYS_SPI_ARGS_SIZE=0x80000
CONFIG_SYS_MAX_FLASH_SECT=512
CONFIG_IS_ENABLED(option)="(config_enabled(CONFIG_VAL(option)) || config_enabled(CONFIG_VAL(option ##_MODULE)))"
CONFIG_SYS_MMCSD_RAW_MODE_KERNEL_SECTOR=0
CONFIG_EHCI_IS_TDI=y
CONFIG_PREBOOT=y
CONFIG_SPL_FS_LOAD_PAYLOAD_NAME="u-boot.img"
